// src/component/MyChart/MyBar.tsx
import * as echarts from 'echarts'
import { EChartsType } from 'echarts'
import { useEffect, useRef } from 'react'

import { defaultStyle } from './initOption'

interface IProps {
  width?: string
  height?: string
  data: any
  style?: any
}

export default function MyBar({
  width = '100%',
  height = '100%',
  data,
  style = defaultStyle
}: IProps) {
  const chartRef = useRef<HTMLDivElement>(null)
  const chart = useRef<EChartsType>()

  useEffect(() => {
    chart.current = echarts.init(chartRef.current)
    window.addEventListener('resize', resize)
    return () => {
      chart.current && echarts.dispose(chart.current)
      window.removeEventListener('resize', resize)
    }
  }, [])

  useEffect(() => {
    renderChart()
  }, [data, style])

  const resize = () => {
    if (!chart.current) return
    chart.current.resize({
      animation: {
        duration: 300,
        easing: 'cubicInOut'
      }
    })
  }

  const renderChart = () => {
    const option = {
      title: {
        text: style.title,
        textStyle: { color: style.tcolor }
      },
      textStyle: { color: style.tcolor },
      color: style.color,
      tooltip: { show: style.tooltipShow },
      legend: {
        show: style.legendShow,
        textStyle: { color: style.tcolor }
      },
      xAxis: {
        type: 'category',
        name: '样本',
        data: data.data?.map((v: any) => v.name)
      },
      yAxis: {
        type: 'value',
        name: '指标分数',
        splitLine: {
          show: true,
          lineStyle: { color: '#222' }
        }
      },
      series: {
        type: 'bar',
        name: data.title,
        data: data.data?.map((v: any) => v.value),
        label: { show: true, position: 'top', color: style.tcolor }
      }
    }
    chart.current && chart.current.setOption(option)
  }

  return <div ref={chartRef} style={{ width, height }}></div>
}

// src/component/MyChart/MyBar.vue
<script>
import * as echarts from 'echarts'

export default {
  name: 'MyBar',
  props: {
    width: { type: String, default: '100%' },
    height: { type: String, default: '100%' },
    cdata: { type: Object },
    cstyle: { type: Object }
  },
  data() {
    return {
      chart: ''
    }
  },
  mounted() {
    this.$nextTick(() => (this.chart = echarts.init(this.$refs.chart)))
    window.addEventListener('resize', this.resize)
  },
  destroyed() {
    echarts.dispose(this.chart)
    window.removeEventListener('resize', this.resize)
  },
  watch: {
    cdata: {
      handler() {
        this.renderChart()
      },
      deep: true
    },
    cstyle: {
      handler() {
        this.renderChart()
      },
      deep: true
    }
  },
  methods: {
    renderChart() {
      const option = {
        title: {
          text: this.cstyle.title,
          textStyle: { color: this.cstyle.tcolor }
        },
        textStyle: { color: this.cstyle.tcolor },
        color: this.cstyle.color,
        tooltip: { show: this.cstyle.tooltipShow },
        legend: {
          show: this.cstyle.legendShow,
          textStyle: { color: this.cstyle.tcolor }
        },
        xAxis: {
          type: 'category',
          name: '样本',
          data: this.cdata.data?.map(v => v.name)
        },
        yAxis: {
          type: 'value',
          name: '指标分数',
          splitLine: {
            show: true,
            lineStyle: { color: '#222' }
          }
        },
        series: {
          type: 'bar',
          name: this.cdata.title,
          data: this.cdata.data?.map(v => v.value),
          label: { show: true, position: 'top', color: this.cstyle.tcolor }
        }
      }
      this.chart.setOption(option)
    },
    resize() {
      this.chart.resize({
        animation: {
          duration: 300,
          easing: 'cubicInOut'
        }
      })
    }
  }
}
</script>

<template>
  <div ref="chart" :style="{ width, height }"></div>
</template>

<style lang="scss" scoped></style>
